name: fromScratch-backend

services:
  database:
    build: ./postgres
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGTZ=Europe/Athens
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fromScratchAPI
    ports:
      - 5432:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  server:
    platform: linux/amd64
    restart: unless-stopped
    build: .
    stop_signal: SIGKILL
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app/source:/app:.
      - TIMEZONE=Europe/Athens
      - 'POSTGRES_USER_CREDS={"USER": "admin", "PASSWORD": "admin"}'
      - POSTGRES_HOST=database
    ports:
      - 8000:8000
    depends_on:
      - database
    working_dir: /app
    volumes:
      - ./source:/app/source

volumes:
  local_postgres_data:
